### ISSUE TITLE
Sandbox MSBuild

### ISSUE THREAD

**Issue by JoshVarty** [CodeConnect/SourceBrowser#69]
As mentioned by Jason [here](https://twitter.com/jasonmalinowski/status/521845061684711424), we need to properly sandbox our use of MSBuild when loading solutions. I'd rather not lose everything on the machine (or worse...).

Unfortunately, I'm not sure what the appropriate steps to take here are. I'm reading up on running partially trusted code in a sandbox, but I'm not sure if this is good enough: http://msdn.microsoft.com/en-us/library/bb763046%28v=vs.110%29.aspx

**Comment by JoshVarty** [comment]
Sounds like that might not work either: https://twitter.com/ThisIsJoshVarty/status/551216170175447041

**Comment by AmadeusW** [comment]
What would we run in the sandbox? **MSBuild**, because the concern is that the build script may contain malicious code? 
Does it mean that the assembly with restricted permissions would be  *Microsoft.CodeAnalysis.Workspaces.Desktop.dll*?

The article says that one of the permissions that can be granted is being able to use a virtual filesystem which is restricted to that assembly only. Either I'm wrong or we will need to devise a mechanism to return SB_Files from that filesystem to the actual filesystem.

**Comment by AmadeusW** [comment]
Whoops, missed Jason's tweet. Low privilege user account sounds like it could do the trick and be relatively straightforward. Let's hear his response about elevation.

**Comment by AmadeusW** [comment]
Working on this in https://github.com/AmadeusW/SourceBrowser/tree/SecureGenerator

The code is done and should work. This will be verified after we successfully update the server to support newest Roslyn DLLs. I will create a pull request with details then.
